### PR TITLE
webserver

### PR DESCRIPTION
**Pull request by Bikaskumar572**
weather website
heroku link : https://bikas-weather-application.herokuapp.com/
github link : https://github.com/Bikaskumar572

### CODE REVIEW

**Comment by Bikaskumar572** [comment]
@shubham9672 , can u please check my project heroku link also provided

**Comment by shubham9672** [comment]
@Bikaskumar572 please add this project to the proper directory

**Comment by Bikaskumar572** [comment]
@shubham9672 , done!

**Comment by Bikaskumar572** [comment]
@shubham9672 , is it ok ?

**Comment by shubham9672** [comment]
@Bikaskumar572 yes this is fine but can you confirm that it is not a node js project.

**Comment by Bikaskumar572** [comment]
@shubham9672 , it uses nodejs but it is mainly focused on frontend (tailwind css)

**Comment by Bikaskumar572** [comment]
@shubham9672 , if u want i can add this to nodejs project, just let me know...

**Comment by Bikaskumar572** [comment]
@shubham9672 , if its ok can u please label it as hacktoberfest ......

**Comment by Bikaskumar572** [comment]
@shubham9672

**Review by shubham9672 — APPROVED** [review]

**Pull request merged**
