### PR TITLE
Weather App

### PR DESCRIPTION
**Pull request by Korak-Sengupta**
A simple weather app made with JS

### CODE REVIEW

**Comment by shubham9672** [comment]
@Korak-Sengupta can you please add a screenshot or provide proper documentation for reference so that I can review it properly.

**Comment by Korak-Sengupta** [comment]
Ok

**Comment by shubham9672** [comment]
@Korak-Sengupta please resolve this conflict also

**Comment by Korak-Sengupta** [comment]
please check now

**Review by shubham9672 — APPROVED** [review]

**Pull request merged**
