### PR TITLE
Sidebar Code added

### PR DESCRIPTION
**Pull request by ShubhamGoyal7125**
Please add `hacktoberfest-accepted` label.
Thank you!!

### CODE REVIEW

**Comment by shubham9672** [comment]
@ShubhamGoyal7125 can you please provide a screen-shot of this sidebar so that I can review it

**Comment by ShubhamGoyal7125** [comment]
Hi @shubham9672 , 

image

**Comment by ShubhamGoyal7125** [comment]
Hi @shubham9672 , please review the screenshot that I have added.

**Comment by shubham9672** [comment]
@ShubhamGoyal7125 please add more content

**Pull request closed without merging**
